/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ug.wzr.client;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.xml.ws.WebServiceRef;
import ug.wzr.Student;
import ug.wzr.StudentService_Service;

/**
 *
 * @author jsarnowski
 */
public class StudenciFrame extends javax.swing.JFrame {

    @WebServiceRef(wsdlLocation = "META-INF/wsdl/localhost_8080/WebService/StudentService.wsdl")
    private static StudentService_Service StudentService;
                    
    private Object[][] data = new Object[][]{};
    private List<Student> studenci;
    private DefaultTableModel model;
    /**
     * Creates new form StudenciFrame
     */
    public StudenciFrame() {
        initComponents();
                
        studenci = getAllStudents();
        data = new Object[studenci.size()][4];
        
                
        //studenciTable = new JTable(new DefaultTableModel(data, columnNames));
        model = (DefaultTableModel) studenciTable.getModel();
                
        for(int i = 0; i < data.length; i++) {
            data[i][0] = studenci.get(i).getNrIndeksu();
            data[i][1] = studenci.get(i).getImie();
            data[i][2] = studenci.get(i).getNazwisko();
            
            model.addRow(data[i]);
        }
                
        studenciTable.setModel(model);
        
        this.setTitle("Studenci");
        this.pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frameTitleLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        studenciTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("StudenciFrame"); // NOI18N

        frameTitleLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        frameTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        frameTitleLabel.setText("Studenci");

        studenciTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numer indeksu", "Imię", "Nazwisko", "Akcje"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        studenciTable.setCellSelectionEnabled(true);
        jScrollPane1.setViewportView(studenciTable);
        studenciTable.getAccessibleContext().setAccessibleName("studenciTable");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(375, 375, 375)
                        .addComponent(frameTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(204, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(frameTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudenciFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudenciFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudenciFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudenciFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {                            
                new StudenciFrame().setVisible(true);
                //for(int i = 0; i < data.length; i++) {
                //   data[i][0] = studenci.get(i).getNrIndeksu();
                //    data[i][1] = studenci.get(i).getImie();
                //    data[i][2] = studenci.get(i).getNazwisko();
                //}
                
                //for(int i = 0; i < data.length; i++) {
                //    for(int j = 0; j < 4; j++) {
                //        System.out.println(data[i][j]);
                //    }
                //}
                
                //for(int i = 0; i < studenci.size(); i++) {
                //    System.out.println("STUDENT " + Integer.toString(i));
                //    System.out.println(studenci.get(i).getNrIndeksu());
                //    System.out.println(studenci.get(i).getImie());
                //   System.out.println(studenci.get(i).getNazwisko());
                //}
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel frameTitleLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable studenciTable;
    // End of variables declaration//GEN-END:variables

    private static Boolean createStudent(int nrIndeksu, java.lang.String imie, java.lang.String nazwisko) {
        // Note that the injected javax.xml.ws.Service reference as well as port objects are not thread safe.
        // If the calling of port operations may lead to race condition some synchronization is required.
        ug.wzr.StudentService port = StudentService.getStudentServicePort();
        return port.createStudent(nrIndeksu, imie, nazwisko);
    }

    private static Student getStudent(int nrIndeksu) {
        // Note that the injected javax.xml.ws.Service reference as well as port objects are not thread safe.
        // If the calling of port operations may lead to race condition some synchronization is required.
        ug.wzr.StudentService port = StudentService.getStudentServicePort();
        return port.getStudent(nrIndeksu);
    }

    private static Boolean updateStudent(int nrIndeksu, java.lang.String imie, java.lang.String nazwisko) {
        // Note that the injected javax.xml.ws.Service reference as well as port objects are not thread safe.
        // If the calling of port operations may lead to race condition some synchronization is required.
        ug.wzr.StudentService port = StudentService.getStudentServicePort();
        return port.updateStudent(nrIndeksu, imie, nazwisko);
    }

    private static boolean deleteStudent(int nrIndeksu) {
        // Note that the injected javax.xml.ws.Service reference as well as port objects are not thread safe.
        // If the calling of port operations may lead to race condition some synchronization is required.
        ug.wzr.StudentService port = StudentService.getStudentServicePort();
        return port.deleteStudent(nrIndeksu);
    }

    private static java.util.List<ug.wzr.Student> getAllStudents() {
        // Note that the injected javax.xml.ws.Service reference as well as port objects are not thread safe.
        // If the calling of port operations may lead to race condition some synchronization is required.
        ug.wzr.StudentService port = StudentService.getStudentServicePort();
        return port.getAllStudents();
    }
}
